Refactor
jlab/bellmanscafe pull request #54
Opened 2024-01-12 13:56 UTC by sjanssen2

2024-01-15 15:47 UTC, Anna-Rehm commented on Bellmansgap.py
>  app.secret_key = "xasdqfghuioiuwqenjdcbjhawbuomcujeq1217846421kopNSJJGWmc8u29"
The secret key should not be open to public as it poses a security threat.
Rather, import from another file and hide that file with .gitignore

2024-01-15 15:59 UTC, sjanssen2 commented on Bellmansgap.py
>  app.secret_key = "xasdqfghuioiuwqenjdcbjhawbuomcujeq1217846421kopNSJJGWmc8u29"
absolutely right. We should also not execute the server in debug mode: [`app.run(debug=True)`](https://github.com/jlab/bellmanscafe/blob/03534e810d18756ae535dc35ad32f8ab15516024/Bellmansgap.py#L88)

2024-01-15 16:17 UTC, Anna-Rehm commented on static/css/style.css
> +  --jlab_lightblue: #89c7f4; /* was: #B8E1A3 */
A bit too light as a bg colour for white script. But this is an aesthetic issue and can be changed down the line :)

2024-01-15 16:23 UTC, Anna-Rehm requested changes
Issue with secret key should be solved before merging, already addressed [here](https://github.com/jlab/bellmanscafe/pull/54#discussion_r1452533442)

2024-01-16 08:37 UTC, sjanssen2 commented on Bellmansgap.py
>  app.secret_key = "xasdqfghuioiuwqenjdcbjhawbuomcujeq1217846421kopNSJJGWmc8u29"
key is moved into `gunicorn_bellmanscafe_conf.py` and changed on the actual serving instance

2024-01-16 08:42 UTC, Anna-Rehm approved these changes

2024-01-16 09:41 UTC, kmaibach approved these changes
I might have missed this but what about all the files generated during one run (the compiled files, the tikz LaTeX file and so on). Are they stored on the server somewhere? Are they just cached and deleted? 
Do we need to think about a good solution or is this already taken care of?

2024-01-16 09:41 UTC, kmaibach commented on static/css/style.css
> +  --jlab_lightblue: #89c7f4; /* was: #B8E1A3 */
the complementary colour of "jlab blue" would be `#b44c00`
which is a darker orange.

could work, but could also look horrible :D 
I tried it on the website but I am not sure what to think of the combination.

Alternatively `#0085e7` might look good being a lighter shade of "jlab blue"

2024-01-16 19:34 UTC, sjanssen2 commented on Bellmansgap.py
>  app.secret_key = "xasdqfghuioiuwqenjdcbjhawbuomcujeq1217846421kopNSJJGWmc8u29"
yes, I am using a new key know - only known in the VM

2024-01-16 19:38 UTC, sjanssen2 commented
> I might have missed this but what about all the files generated during one run (the compiled files, the tikz LaTeX file and so on). Are they stored on the server somewhere? Are they just cached and deleted? Do we need to think about a good solution or is this already taken care of?

These files are stored in https://github.com/jlab/bellmanscafe/blob/8b153feb277d7f2ee66297d880f288502ed2a576/gunicorn.conf.py#L44 and used as a cache. The cache directory depends on a) the `gapc --version` b) a hash sum of the *.gap file and c) another hash sum of the user track input. Updating one of these components automatically leads to other directories.
Currently, I am not limiting the total size of the cache as I do not assume too many users. We can add this once we hit the disk quota ;-)

2024-01-16 19:45 UTC, sjanssen2 commented
> Nice work! Server is looking sharp.

thanks :-)

> I would consider adding the python package markdown to the requirements in the README.txt Maybe even add Flask. gunicorn and markdown to a separate requirements.txt

I feel we need to completely rewrite the readme.md :-/

> If we do this than the Dockerfile would also need to be adjusted.

Ideally, we would "dockerize" the server, such that the BCF can easily maintain this server for us. I have not yet found the time to complete this task.
 
> If needed the elmamun example can be sharpened using AI service https://neural.love/image-sharpen

I don't have any credits but would love to see the result.

2024-01-16 19:46 UTC, merged